#  _____             _   _     _____      _       _
# |  __ \           | | | |   |  __ \    (_)     | |
# | |  | | ___  __ _| |_| |__ | |__) |__  _ _ __ | |_
# | |  | |/ _ \/ _` | __| '_ \|  ___/ _ \| | '_ \| __|
# | |__| |  __/ (_| | |_| | | | |  | (_) | | | | | |_
# |_____/ \___|\__,_|\__|_| |_|_|   \___/|_|_| |_|\__|
#                                            By Spazzinq

# Discord: https://spazzinq.org/discord
# Github: https://github.com/Spazzinq/DeathPoint/issues

# Before you leave a negative review:
# ✓ Read through ALL the information in this configuration
# ✓ Contact me on Discord (if the config does not solve your problem)
# ✓ Create an official bug report/feature request on GitHub

#  ___  _         _
# |   \(_)____ __| |__ _ _  _
# | |) | (_-< '_ \ / _` | || |
# |___/|_/__/ .__/_\__,_|\_, |
#           |_|          |__/

# Format of hoverable death message
# %x% = x, %y% = y, %z% = z, %world% = world, %player% = player
hover:
- "&c%player% died at %x%, %y%, %z%"
- "&cin %world%"

#  _
# | |   __ _ _ _  __ _ _  _ __ _ __ _ ___
# | |__/ _` | ' \/ _` | || / _` / _` / -_)
# |____\__,_|_||_\__, |\_,_\__,_\__, \___|
#                |___/          |___/
no_permission: "&cYou don't have permission!"

#  ___               _       _
# | _ \___ _ _ _ __ (_)_____(_)___ _ _  ___
# |  _/ -_) '_| '  \| (_-<_-< / _ \ ' \(_-<
# |_| \___|_| |_|_|_|_/__/__/_\___/_||_/__/
#
# deathpoint.admin - Permission for reloading the plugin
# deathpoint.disable - Disables the hoverable death message