name: DeathPoint
main: org.Spazzinq.DeathPoint.DeathPoint
version: ${project.version}
api-version: 1.13
description: "Sends the death message with a hoverable location"
author: Spazzinq

commands:
  deathpoint:
    description: "Base command for reloading the plugin"

permissions:
  deathpoint.admin:
    description: "Permission for reloading the plugin"
    default: op
  deathpoint.disable:
    description: "Disables the hoverable death message"
    default: false